name: Setup
runs:
    using: composite
    steps:
        - name: Use actions/checkout@v4
          uses: actions/checkout@v4
          with:
              # don’t save GITHUB_TOKEN to .git/config; use credential helper instead
              # because we don’t want git commands on other repositories to use GITHUB_TOKEN
              # (e.g. yarn install runs git ls-remote ssh://git@github.com/themaven-net/tempest-common.git)
              persist-credentials: false
