# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Use actions/checkout@v4
        uses: actions/checkout@v4
        with:
            # don’t save GITHUB_TOKEN to .git/config; use credential helper instead
            # because we don’t want git commands on other repositories to use GITHUB_TOKEN
            # (e.g. yarn install runs git ls-remote ssh://git@github.com/themaven-net/tempest-common.git)
            persist-credentials: false
      - name: Set up environment
        uses: ./.github/actions/setup

        # Dump contexts
      # Copied from https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-printing-context-information-to-the-log
      - name: Dump env
        # dump the env that will be used by Context used by GitHub Actions @actions/github
        # https://github.com/actions/toolkit/blob/2b97eb3192ed27ad81a555e87f3f9de61c11a213/packages/github/src/context.ts  
        run: env
      - name: Dump github env (is empty unless you explicitly set env in a job or step)
        run: echo "$WORKFLOW_ENV"
        env:
          WORKFLOW_ENV: ${{ toJson(env) }}
      - name: dump event payload
        run: cat "$GITHUB_EVENT_PATH"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      

          # Runs a set of commands using the runners shell
      - name: fetch issue events
        run: |
          # https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
             /repos/${{github.repository}}/issues/${{ github.event.pull_request.number || '1' }}/events
